---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kustomize-nginx
  template:
    metadata:
      labels:
        app: kustomize-nginx
        testService: service-1
    spec:
      containers:
      - name: kustomize-nginx
        image: nginx
        ports:
        - containerPort: 88
        volumeMounts:
        - name: nginx-index-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-config
        configMap:
          name: nginx-config-1